<a href="https://colab.research.google.com/github/felicity8899/mlops/blob/main/Homework_1_Introduction_to_Machine_Learningipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd

In [4]:
print(pd.__version__)

2.2.3

In [7]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [8]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [9]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [10]:
set(df.fuel_type)

{'Diesel', 'Gasoline', 'Hybrid'}

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [23]:
df['horsepower'] = df.horsepower.fillna(max(df.horsepower))
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,261.42290,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,31.34511,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.00000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,241.00000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,257.00000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,276.00000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.00000,5460.000000,23.800000,41.200000

In [39]:
X = df[['vehicle_weight','model_year']].sort_values(by=['model_year'], ascending=True).head(7)

In [40]:
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = XTX_inv.dot(X.T).dot(y)

print("The sum of the elements in w is:", w.sum())

The sum of the elements in w is: 0.11797868388720562